# Generated by Django 4.2.5 on 2023-09-22 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_venda_rename_produtos_produto_rename_users_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'isVendedor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='venda_cliente', to='app.user'),
        ),
    ]
